const topNav = new NavigationBarGenerator();
topNav.makeTopBar();
topNav.addItem("Outerwear", "./examples2.html");
topNav.addItem("Swimwear", "");
topNav.addItem("Activewear", "");
topNav.addItem("Sleepwear", "");
topNav.addItem("Shoes", "");
topNav.addItem("Bags", "");
topNav.addSearchField();
topNav.spaceEqually();

const bottomNav = new NavigationBarGenerator();
bottomNav.makeBottomBar();
bottomNav.addItem("New Arrivals", "", "L");
bottomNav.addItem("Most Popular", "", "L");
bottomNav.addItem("Free Shipping", "", "M");
bottomNav.addItem("Return Policy", "", "M");
bottomNav.addItem("Shopping Cart", "", "R");
bottomNav.addItem("My Account", "", "R");
bottomNav.addItem("Clearence", "");
bottomNav.addSearchField();
bottomNav.changeBarColor("Lavender");
